-- Carga inicial de vacantes desde 'Hiring Plan Services 2026'.
-- Generado a partir de Pipeline_Data_v1.0.xlsx. Ejecutar UNA SOLA VEZ
-- (no tiene protección contra duplicados si se corre dos veces).
--
-- El trigger que autocompleta fecha_cierre_proceso al llegar a un estado
-- terminal se desactiva durante esta carga: varias búsquedas Hired/
-- Cancelled de la planilla no tienen fecha de cierre real, y dejar el
-- trigger activo la reemplazaría por la fecha de hoy, inflando el Time
-- To Fill. Mejor un campo vacío (a completar a mano si se conoce la
-- fecha real) que un dato incorrecto.
alter table vacantes disable trigger antes_de_insertar_vacante;

insert into vacantes (titulo, cliente_o_area, estado_id, fecha_inicio_proceso, fecha_cierre_proceso, fecha_prevista_ingreso_hm, fecha_ingreso_confirmada, notas, trimestre, proyecto, nivel, tipo_oportunidad, pais, bu, hiring_manager_nombre, reclutador_nombre_importado, perfiles_presentados, candidato_ingresado_nombre)
values
  ('Team Lead', 'Mercado Libre', (select id from estados_vacante where nombre = 'Stand By'), '2025-10-01', null, null, null, null, 'Q1', null, 'Level 8', 'Qualer', 'ARG', 'Services', 'Natalia Crespo', 'Jazmín Cuello', 'en búsqueda', null),
  ('AI Solution Lead', 'IA LAB', (select id from estados_vacante where nombre = 'Hired'), '2025-12-01', null, null, null, null, 'Q1', null, 'Level 8', 'Qualer', 'ARG', 'Services', 'Agustin Gaig', 'Jazmín Cuello', 'Offer acepted: Kevin Kovacs 24/2', 'Kevin Kovacs'),
  ('Data Governance', 'ELEA', (select id from estados_vacante where nombre = 'Hired'), '2025-10-23', null, null, null, null, 'Q1', 'C0184P0020 - Laboratorio Elea - Acompañamiento BI - 25', 'Level 6', 'Qualer', 'ARG', 'Services', 'Julian Cappa', 'Jazmín Cuello', 'Josfina Grigera 02/02', null),
  ('Data Visualization Lead', 'INSUD', (select id from estados_vacante where nombre = 'Hired'), '2025-01-01', '2026-02-23', null, null, null, 'Q1', 'Reemplazo Candela - Se genera la Propuesta una vez que estemos ok con candidato', 'Level 8', 'Qualer', 'ESP', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'El/La Candidata deberá estar en Madrid para poder asistir a la oficina de INSUD .Afinar la búsqueda de un perfil con los siguientes criterios mínimos: mínimo 7 años de experiencia en Power BI, arquitectura de datos o campos relacionados; al menos una certificación oficial de Microsoft (por ejemplo, PL-300: Microsoft Power BI Data Analyst Associate. Power BI Data Analyst, Fabric Analytics Engineer); sólida experiencia en Power BI (DAX, Power Query, Service); y experiencia en modelado de datos para Power BI.', 'Javier Higuera Porteros'),
  ('CP4D', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2025-01-01', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 6', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'Clickup con descripción', null),
  ('AI Developer', 'IA LAB', (select id from estados_vacante where nombre = 'Hired'), '2026-01-13', null, null, null, null, 'Q1', null, 'Level 7', 'Qualer', 'ARG', 'Services', 'Agustin Gaig', 'Jazmín Cuello', 'Ingreso 2/2 - Franco Ferrer', null),
  ('Data Engineer', 'Hibrids', (select id from estados_vacante where nombre = 'Cancelled'), '2025-11-20', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 5', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Jazmín Cuello', 'Frenado de parte de cliente hasta nuevo aviso 27/1', null),
  ('Points Operations & Analytics Senior', 'Hibrids', (select id from estados_vacante where nombre = 'Cancelled'), null, null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 8', 'Freelance', null, 'Services', null, 'Jazmín Cuello', 'Frenado de parte de cliente hasta nuevo aviso 27/1', null),
  ('PBI Admin - Soporte', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), null, null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 7', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'Detalle en Clickup - Reeamplazo de licencia en Marzo/Abil', null),
  ('Data Engineer', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2025-01-01', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 6', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'experto de Cognos con conocimientos avanzados en PowerBI. Sería para trabajar 4 horas al día, de 08:00 a 12:00 (hora de España).', null),
  ('Cybersecurity Specialist', 'INSUD', (select id from estados_vacante where nombre = 'Hired'), '2025-01-01', null, null, null, null, 'Q1', null, 'Level 8', 'Talento Tech', 'ESP', 'Services', 'Natalia Crespo', 'Jazmín Cuello', 'Talento Tech - Ingreso Gloria 12/01', null),
  ('Data Engineer', 'INSUD', (select id from estados_vacante where nombre = 'On Going'), '2025-01-01', null, null, null, null, 'Q1', null, 'Level 8', 'Talento Tech', 'ESP', 'Services', 'Natalia Crespo', null, 'Rechazo de offer de Alvaro - pending nuevo perfil de parte de INSUD', null),
  ('Data Engineer', 'INSUD', (select id from estados_vacante where nombre = 'On Going'), null, null, null, null, null, 'Q1', null, null, 'Talento Tech', 'ESP', 'Services', 'Natalia Crespo', null, null, null),
  ('Data Engineer', 'Xiromed', (select id from estados_vacante where nombre = 'Cancelled'), '2025-01-01', null, null, null, null, 'Q1', 'C0227P0004 - Xiromed Suecia - Dedicated Supply Report Team - Oct-Dec 25', 'Level 7', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Azure Data Factory - comunicación con Capacity por posibles asignaciones internas: 1-Gian Paniagua 2- Pachu 3- Agustin Morales', null),
  ('SQL', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2025-01-19', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 5', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Jazmín Cuello', '9 meses PT de 9 a 13 horario España - SQL avanzado', null),
  ('Data Analyst', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2026-01-13', null, null, null, null, 'Q1', 'C0195P0021 - Logicalis - Migración DataBricks - Q1 26', 'Level 7', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'cuatro meses. REquiere Guardias, SQL SSIS, Databricks. PBI (Plus) requiere entrevista con el cliente', null),
  ('Data Scientist', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-01-27', '2026-02-23', null, null, null, 'Q1', 'C0027P0293 - Mercado Libre - People - S1 26', 'Level 8', 'Qualer', 'ARG', 'Services', 'Nicolas Indiviglia', 'Jazmín Cuello', null, 'Natalia Orozco'),
  ('PBI Ssr', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2026-01-26', null, null, null, null, 'Q1', null, 'Level 6', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', null, null),
  ('Data Engineer', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-01-29', null, null, null, null, 'Q1', 'C0027P0293 - Mercado Libre - People - S1 26', 'Level 6', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Jazmín Cuello', 'Cristian Denaro, Fabricio Sobral, Mauricio Rogstano, Jorge Uballes', null),
  ('Data Engineer', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-02', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 6', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'exp en powercenter proyectro que empezaríamos entre mediados y finales de febrero, con unos 4 o 5 meses de duración', null),
  ('Data Analyst', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-03', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 6', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'tarifa a 1 año con +1 opcional de renovación, nos debes dar tarifa para el primero y para el posible 2º año.

 

Creemos que sería necesario un horario intermedio entre Argentina y España, aunque vamos a reconfirmar con cliente.', null),
  ('DESARROLLADOR ECOSISTEMA AWS', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-03', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 6', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'tarifa a 1 año con +1 opcional de renovación, nos debes dar tarifa para el primero y para el posible 2º año.

 

Creemos que sería necesario un horario intermedio entre Argentina y España, aunque vamos a reconfirmar con cliente.', null),
  ('DESARROLLADOR SOLUCIONES EN MICROSOFT POWER PLATFORM', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-03', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 6', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Jazmín Cuello', 'tarifa a 1 año con +1 opcional de renovación, nos debes dar tarifa para el primero y para el posible 2º año.

 

Creemos que sería necesario un horario intermedio entre Argentina y España, aunque vamos a reconfirmar con cliente.', null),
  ('Data Engineer', 'ELEA', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-09', null, null, null, null, 'Q1', 'OPORTUNIDAD PREVENTA', 'Level 6', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Jazmín Cuello', null, null),
  ('Data Engineer Ssr', 'Labyes', (select id from estados_vacante where nombre = 'Hired'), '2026-02-09', '2026-02-19', null, null, null, 'Q1', 'C0143P0032 - Labyes - Integración Mercadata y Plugger - Sentinel - Ene 26', 'Level 4', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', null, 'Alvarez Lucas'),
  ('Data Developer', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-02-23', null, null, null, null, 'Q1', 'C0027P0314 - Mercado Libre - Acompañamiento BI - RTR - S1 26', 'Level 3', 'Qualer', 'ARG', 'Services', 'Nicolas Indiviglia', 'Karen Cilli', 'Presentación Perfiles Jr | MELI', 'Gambarte Emiliano'),
  ('Power BI -', 'Exceltis', (select id from estados_vacante where nombre = 'Hired'), '2026-03-03', '2026-03-05', '2026-03-09', '2026-03-09', null, 'Q1', 'C0238P0001 - Exeltis USA - Financial Dashboard', 'Level 5', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', 'Presentación Perfiles Sr PWBI | Exceltis', 'Bustamante Nicolás'),
  ('AI Developer', 'IA LAB', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-26', null, null, null, null, 'Q1', null, null, null, 'ARG', 'Services', 'Agustin Gaig', 'Karen Cilli', 'Pipeline AI Solutions Lead', null),
  ('Data Engineer', 'Logicalis', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-25', null, null, null, 'Perfiles presentados', 'Q1', 'C0195P0021 - Logicalis - Migración DataBricks - Q1 26', 'Level 7', 'Freelance', 'ARG', 'Services', 'Camila Mariño', 'Karen Cilli', 'Presentación Perfiles SSIS | Logicalis', null),
  ('Data Developer', 'Grupo INSUD', (select id from estados_vacante where nombre = 'Hired'), '2026-02-26', '2026-03-17', null, null, 'Perfiles presentados', 'Q1', null, 'Level 2', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Karen Cilli', 'Presentación Perfiles Jr PWBI | INSUD', 'Castillo Ivan'),
  ('Data Viz - Tableau', 'Exceltis', (select id from estados_vacante where nombre = 'Hired'), '2026-03-16', '2026-03-17', null, null, null, 'Q1', 'C0238P0002 - Exeltis USA - Tableau Source Re-pointing & Speaker Event Data Collection', 'Level 4', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', 'Eric (Chicho Boy)', 'Sakowski Eric'),
  ('Data Scientist', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-02-23', '2026-03-19', null, null, null, 'Q1', 'C0027P0305 - Mercado Libre - People - Acompañamiento BI - S1 26', 'Level 6', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Karen Cilli', 'Fagioli Gianfranco', 'Fagioli Gianfranco'),
  ('Sr Data Engineer', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-02-23', '2026-03-20', null, null, null, 'Q2', 'C0027P0305 - Mercado Libre - People - Acompañamiento BI - S1 26', 'Level 6', 'Qualer', 'ARG', 'Services', 'Nicolas Indiviglia', 'Karen Cilli', 'Presentación Perfiles Sr Data Engineer | MELI', 'Monza Augusto'),
  ('Team Lead', 'Latam', (select id from estados_vacante where nombre = 'Hired'), '2026-02-20', '2026-03-25', null, null, null, 'Q1', null, 'Level 8', 'Qualer', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', 'Presentación Perfiles Sr Data Lead | Insud & Latam', 'Moreno Justina'),
  ('Data Engineer Ssr', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-03-26', '2026-03-31', null, null, null, 'Q2', 'C0027P0313- Corp + FINOPS', 'Level 4', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Karen Cilli', null, 'García Alejandro'),
  ('Data Engineer Ssr', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-03-30', '2026-04-08', null, null, null, 'Q2', 'C0027P0290 - Mercado Libre - GROW FPS - Cierre de SubBU - Nov-May 26', 'Level 4', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Karen Cilli', null, 'Melamed Hernan'),
  ('Data Engineer Ssr', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-03-31', '2026-04-09', null, null, null, 'Q3', 'C0027P0313- Corp + FINOPS', 'Level 5', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Karen Cilli', null, 'Gimenez Gustavo'),
  ('Desarollador Java', 'QUANAM', (select id from estados_vacante where nombre = 'Hired'), '2026-03-12', '2026-04-24', null, '2026-05-04', null, 'Q1', null, 'Level 4', 'Freelance', 'ARG', 'Services', null, 'Karen Cilli', null, 'Prono Martin'),
  ('Team Lead', 'INSUD', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-20', null, null, null, 'Generar entrevistas: Sofía y Franco', 'Q1', null, 'Level 8', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Karen Cilli', 'Presentación Perfiles Sr Data Lead | Insud & Latam', null),
  ('Data Analyst', 'INSUD', (select id from estados_vacante where nombre = 'Cancelled'), '2026-02-25', null, null, null, 'Generar entrevistas', 'Q1', null, 'Level 5', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Karen Cilli', 'Presentación Perfiles Sr Data Analyst | Insud', null),
  ('Power BI -', 'BISA', (select id from estados_vacante where nombre = 'Cancelled'), '2026-04-07', null, null, null, 'Perfiles presentados. Coordinar entrevista con CCappato', 'Q2', null, 'Level 6', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', 'Presentación Perfiles PWBI | BISA', null),
  ('Data Engineer Ssr', 'FIFCO', (select id from estados_vacante where nombre = 'Hired'), '2026-04-27', '2026-05-06', null, '2026-05-08', null, 'Q2', 'C0172P0082 - Heineken CR / Bebidas Florida FIFCO - Ajustes Club Fill + Loyalty', 'Level 4', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', null, 'Peña Dylan'),
  ('Data Scientist', 'Mercado Libre', (select id from estados_vacante where nombre = 'Cancelled'), '2026-05-06', null, null, null, null, 'Q2', null, 'Level 5', 'Freelance', 'ARG', 'Services', 'Nicolas Indiviglia', 'Karen Cilli', 'Carla - perfil Chicho', null),
  ('Loyalty Manager', null, (select id from estados_vacante where nombre = 'Cancelled'), '2026-04-23', null, null, null, null, 'Q2', null, 'Level 10', 'Freelance', 'ARG', 'Services', 'Facundo Belgrano', 'Karen Cilli', 'Santiago Harasic
Laura Bellina', null),
  ('Data Engineer', 'Exceltis', (select id from estados_vacante where nombre = 'Hired'), '2026-06-23', '2026-06-25', null, null, null, 'Q2', 'C0238P0004 - Exeltis USA- Financial Dashboard Evolution - Data Team JUN 26', 'Level 4', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', null, 'Rebolini Jeronimo'),
  ('Data Scientist', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-06-30', '2026-08-05', null, null, null, 'Q3', null, 'Level 6', 'Freelance', 'ARG', 'Services', 'Noelia Brath', 'Karen Cilli', '- Frank (perfil elías)', 'Piedra Frank'),
  ('Data Governance', 'INSUD', (select id from estados_vacante where nombre = 'Hired'), '2026-07-01', '2026-07-20', null, null, null, 'Q3', null, 'Level 6', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Amalia galeano', null),
  ('IT Analyst', 'IT Support', (select id from estados_vacante where nombre = 'Hired'), '2026-07-01', '2026-07-27', null, null, null, 'Q3', null, 'Level 2', 'Qualer', 'ARG', 'Services', 'Agustin Gaig', 'Jazmín Cuello', null, null),
  ('Account Executive', 'New Names', (select id from estados_vacante where nombre = 'On Going'), '2026-06-18', null, null, null, null, 'Q3', 'N/A', 'Level 6', 'Qualer', 'ESP', 'Comercial', 'Fernando Manjarín', 'Jazmín Cuello', 'Perfiles Sales 2026', null),
  ('Account Executive', 'New Names', (select id from estados_vacante where nombre = 'On Going'), '2026-06-18', null, null, null, null, 'Q3', 'N/A', 'Level 6', 'Qualer', 'MX', 'Comercial', 'Fernando Manjarín', 'Jazmín Cuello', 'Perfiles Sales 2026', null),
  ('Prospection Lead', 'New Names', (select id from estados_vacante where nombre = 'On Going'), '2026-06-18', null, null, null, 'En el medio de la búsqueda se canceló y luego se reabrió', 'Q3', 'N/A', 'Level 4', 'Qualer', 'ARG', 'Services', 'Fernando Manjarín', 'Jazmín Cuello', 'Guadalupe Olivera, Franco Faga, Rocio Quispe', null),
  ('Data Architect', 'INSUD', (select id from estados_vacante where nombre = 'Cancelled'), null, null, null, null, null, 'Q3', null, 'Level 7', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', null, null, null),
  ('Power BI -', 'Kimberly Clark', (select id from estados_vacante where nombre = 'Advanced'), '2026-07-13', null, null, null, null, 'Q3', 'C0075P0054 - Kimberly Clark - Power BI Apps Maintenance & Upgrades - Q1 26', 'Level 5', 'Freelance', 'ARG', 'Services', 'Noelia Brath', 'Karen Cilli', 'Cecilia Bordon y Carolina Cappato', null),
  ('Data Scientist', 'ELEA', (select id from estados_vacante where nombre = 'Cancelled'), '2026-07-21', null, null, null, null, 'Q3', 'N/A', 'Level 6', 'Talento Tech', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', 'Perfiles DS | ELEA', null),
  ('Senior Full Stack Developer', 'Hibrids', (select id from estados_vacante where nombre = 'Cancelled'), '2026-07-21', null, null, null, null, 'Q3', 'N/A', 'Level 6', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', 'Perfiles pedidos a Elias', null),
  ('Senior DevOps & Backend Developer', 'Hibrids', (select id from estados_vacante where nombre = 'Cancelled'), '2026-07-21', null, null, null, null, 'Q3', 'N/A', 'Level 6', 'Freelance', 'ARG', 'Services', 'Julian Cappa', 'Karen Cilli', 'Perfiles pedidos a Elias', null),
  ('Data Analyst', 'INSUD', (select id from estados_vacante where nombre = 'Hired'), '2026-07-20', null, null, null, null, 'Q3', null, 'Level 6', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Lucas Foresto y Sergio Sanchez', null),
  ('Data Engineer', 'Xiromed', (select id from estados_vacante where nombre = 'Job Offer'), '2026-07-24', null, null, null, null, 'Q3', 'C0227P0008 - Xiromed Suecia - Dedicated Needs - Xirohub - Ago-Nov 26', 'Level 6', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Martin Mesaglio', null),
  ('Data Analyst', 'INSUD', (select id from estados_vacante where nombre = 'Job Offer'), '2026-07-24', null, null, null, null, 'Q3', 'Chemo', 'Level 6', 'Qualer', 'ESP', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Florencia Perez , Noelia Navarro, Fernando Burrone', null),
  ('Data Viz INSUD', 'INSUD', (select id from estados_vacante where nombre = 'Cancelled'), '2026-07-24', null, null, null, null, 'Q3', null, 'Level 6', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Se cubre con movimiento interno: Martin Hernadez', null),
  ('Data Manager', 'INSUD', (select id from estados_vacante where nombre = 'On Going'), '2026-07-28', null, null, null, null, 'Q3', 'N/A', 'Level 8', 'Qualer', 'ESP', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Pipeline Data Manager | Insud', null),
  ('AI Developer', 'IA LAB', (select id from estados_vacante where nombre = 'On Going'), '2026-07-24', null, null, null, null, 'Q3', 'N/A', 'Level 4', 'Qualer', 'ARG', 'IA LAB', 'Agustin Gaig', 'Jazmín Cuello', 'Pipeline Team Agentes', null),
  ('Data Engineer', 'Grupo INSUD', (select id from estados_vacante where nombre = 'Hired'), null, null, null, null, null, 'Q3', 'Migración INSUD QlikView', 'Level 6', 'Qualer', 'ARG', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', 'Ver si aplica NSorichetti', null),
  ('Data Engineer', 'Mercado Libre', (select id from estados_vacante where nombre = 'Hired'), '2026-07-13', '2026-08-07', null, null, 'Hernan Melamed', 'Q3', 'C0027P0324 - Mercado Libre - People - Acompañamiento BI - S2 26', 'Level 6', 'Freelance', 'ARG', 'Services', 'Noelia Brath', 'Karen Cilli', null, null),
  ('Data Engineer', 'Logicalis', (select id from estados_vacante where nombre = 'Advanced'), '2026-07-28', null, null, null, null, 'Q3', 'C0241P0022 - Logicalis - Codere - Data Team en Tecnologías MS - 26', 'Level 6', 'Freelance', 'ARG', 'Services', 'Correa Patricio', 'Karen Cilli', 'Perfiles presentados a Pato Correa', null),
  ('Data Architect', 'INSUD', (select id from estados_vacante where nombre = 'Kick Off'), '2026-08-13', null, null, null, null, 'Q3', 'Chemo', 'Level 6', 'Qualer', 'ESP', 'Services', 'Pablo Avedaño', 'Jazmín Cuello', null, null),
  ('Data Scientist Mampower', 'INSUD', (select id from estados_vacante where nombre = 'Kick Off'), '2026-08-06', null, null, null, null, 'Q3', 'N/A', 'Level 6', 'Manpower', 'ESP', 'N/A', 'Irusta Judith', 'Karen Cilli', null, null),
  ('Data Engineer Mampower', 'INSUD', (select id from estados_vacante where nombre = 'Kick Off'), '2026-08-06', null, null, null, null, 'Q3', 'N/A', 'Level 6', 'Manpower', 'ESP', 'N/A', 'Irusta Judith', 'Jazmín Cuello', null, null),
  ('Sr Testing Data Analyst', 'Abiomed', (select id from estados_vacante where nombre = 'Advanced'), '2026-08-18', null, null, null, 'Perfil: Sr Testing Data Analyst
Reporta a: Matías (QA)
Requisitos:
SQL avanzado
Inglés avanzado - Requisito, dialogos a diario con el equipo Cliente
Atlassian suite: Jira, Confluence y Bitbucket
Capacidad para relevar y gestionar necesidades funcionales con stakeholders internos (incluye manejo de SharePoint) 
Deseable (nice to have):
AWS Console: Redshift, Athena, S3 y Terraform', 'Q3', null, 'Level 6', 'Qualer', 'ARG', 'Services', 'Julian Cappa', 'Jazmín Cuello', 'Dalila Gonzalez', null);

alter table vacantes enable trigger antes_de_insertar_vacante;
